language: crystal
notificiations:
  email: false
env:
  global:
    secure: fLxTBgsnytBaC8iML2x+S4UP/bJnXsXddxPqS8NKjJ7PNZ4oIF7BtzqrmG2OAElAwZDZfskU9mbiyokE1jf8GY/VyZt79k3wWPpXBZCUnUzC3Q35T90NwX+T0JEm7DbSowkCy/R9An1noEaNeHnRehren35wQEjH5VCX/4BBMATDQtt47LEs9S8vk3cmzu8oeg6UYY3fiqK79VG8um2VySeIcdMif+JlaMDAPNMh3dokGV9z05hNWGS3MkJtKqr6kPUOVi+CPMImwSg5x4UijmlCDg++A+HJvievwLwcdWbmsA0NFMzVkFAUPAhwuYf1TU7U42v2AorOevA/xHKTFCZwSfw6rRuoQT76KuijJGbejTOvvu9pA5oxKM3pUM3Sg2H1vyh8Hj1SIesMb5V0O9xW/zMz1dwYmOyyLQvvSCIhiGEE/YfIPmQ7bdi7sS2NaI9VrgIzNvulzz/a5MCvjOUFD0wHvJ/ZwWVlgL/YRTfTtD9lRjjuXeqywsH3T9BX6XTSq6LxEQ5BE4tRqg5llQahDTQMkYp1gULHc14GM5ca/Vyiu8LRSv5cOz7Z9+1a799kJpKOKuRGCT3p3ibjYu8dkiwbTchy5LO6izFOE5gWc/LIPkXggM+XKjX7l4dSTS/rFD7zGWJBwha5ivrUdXzV0b2Oaxtc8jIFTEGwUtM=
